name: Delete Merged Branches

on:
  push:
    branches:
      - master  # Trigger the action when something is pushed to the master branch

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure all merged PRs are included

      - name: Delete merged branches excluding the last merged one
        run: |
          # Get the merged branches into the master branch
          echo "Identifying merged branches to delete from master..."
          
          # Get the list of merged branches excluding the most recent merge
          merged_branches=$(git log --merges --oneline master | grep -E 'Merge pull request' | awk -F'from ' '{print $2}' | sed 's|^[^/]*/||')
          
          # Get the total number of merged branches
          total_branches=$(echo "$merged_branches" | wc -l)
          
          # Skip the last branch (most recent merge)
          branches_to_delete=$(echo "$merged_branches" | head -n $(($total_branches - 1)))

          # Print the branches to be deleted
          echo "Branches to delete: $branches_to_delete"

          # Loop through and delete the branches
          for branch in $branches_to_delete; do
            # Check if the branch exists locally
            if git show-ref --verify --quiet refs/heads/"$branch"; then
              echo "Deleting local branch: $branch"
              git branch -d "$branch" || git branch -D "$branch"
            else
              echo "Branch $branch does not exist locally, skipping..."
            fi

            # Check if the branch exists remotely
            if git ls-remote --exit-code --heads origin "$branch"; then
              echo "Deleting remote branch: $branch"
              git push origin --delete "$branch" || echo "Failed to delete remote branch $branch."
            else
              echo "Branch $branch does not exist remotely, skipping..."
            fi
          done
